### PR TITLE
Merge projects, update cats and scalaz and add flatmaprec

### PR DESCRIPTION
**Pull request by edmundnoble**
Rejig to shims to make it work with cats 0.8.1 and Scalaz 7.2.7, as well as Scala.js. I'm not sure how much works exactly, but it seems to be compiling both JS and JVM. The tests only run on the JVM, because they're specs2.

### CODE REVIEW

**Comment by sellout** [comment]
Matryoshka needs like _all_ of these changes.

**Comment by djspiewak** [comment]
Build failed on 2.10.6.

As a sidebar, this PR removes support for scalaz 7.1.  Is that a step we want to take?

**Comment by edmundnoble** [comment]
@djspiewak There is no JS artifact for scalaz 7.1, and 7.1 and 7.2 diverge as far as the BindRec business. I'd have had to make the two not compatible with each other, and move some code from scalaz into the scalaz71 and scalaz72 projects. Do you think that's worth it over removing support?

**Comment by djspiewak** [comment]
> I'd have had to make the two not compatible with each other, and move some code from scalaz into the scalaz71 and scalaz72 projects. Do you think that's worth it over removing support?

Not worth it.  :-)

**Comment by edmundnoble** [comment]
@djspiewak Is there anything you'd like me to put in this PR before it's mergeable, or is this okay to merge?

**Comment by djspiewak** [comment]
@edmundnoble Sorry for the delay.  I think this is ok to merge.  I'll take care of it later today.  I'm also going to drop support for 2.10 and add support for 2.12, since dealing with non-trivial compiler version-specific implicit resolution issues doesn't seem like it would be worth it, all things considered.  :-)

**Pull request merged**
